version: '3.8'
networks:
  web:
    external: true
services:
    dfdemo:
        build: .
        environment:
            - GO_ENV=production
            - SESSION_SECRET=randomsecret
        restart: always
        volumes:
            - .env:/bin/.env
        ports:
            - "3000:3000"
        labels:
            - traefik.http.routers.blog.rule=Host(`demo-partenaire.dossierfacile.fr`)
            - traefik.http.routers.blog.tls=true
            - traefik.http.routers.blog.tls.certresolver=lets-encrypt
            - traefik.port=80
        networks:
            - web
