version: '3.8'
services:
    dfdemo:
        build: .
        network_mode: bridge
        environment:
            - GO_ENV=production
        restart: always
        volumes:
            - .env:/bin/.env
        ports:
            - "80:3000"
            - "443:3000"
