version: '3.8'
services:
    dfdemo:
        build: .
        environment:
            - GO_ENV=production
            - SESSION_SECRET=randomsecret
        restart: always
        env_file:
            - .env
        ports:
            - "3000:3000"
        labels:
            - traefik.http.routers.blog.rule=Host(`demo-partenaire.dossierfacile.fr`)
            - traefik.http.routers.blog.tls=true
            - traefik.http.routers.blog.tls.certresolver=lets-encrypt
            - traefik.port=80
        network_mode: bridge
