version: '3.8'
services:
    dfdemo:
        build: .
        network_mode: bridge
        environment:
            - GO_ENV=production
            - SESSION_SECRET=randomsecret
        restart: always
        volumes:
            - .env:/bin/.env
        ports:
            - "3000:3000"
